# Writes BuildInfo.h: the commit this binary was built from (S26).
#
# Run at every build, not at configure time: a commit read when CMake last
# configured would be the wrong one after any later commit built
# incrementally. The header is rewritten only when its content changes, so an
# unchanged commit recompiles nothing.
#
#   cmake -DSOURCE=<repository> -DOUTPUT=<header> -P DawBuildInfo.cmake

set(commit "inconnu")
set(modified 0)
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse --short=7 HEAD
        WORKING_DIRECTORY "${SOURCE}"
        OUTPUT_VARIABLE read
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE failed
        ERROR_QUIET)
    if(NOT failed AND read)
        set(commit "${read}")
    endif()
    # Tracked files changed since that commit: the binary is not that commit.
    execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
        WORKING_DIRECTORY "${SOURCE}"
        OUTPUT_VARIABLE changes
        RESULT_VARIABLE failed
        ERROR_QUIET)
    if(NOT failed AND changes)
        set(modified 1)
    endif()
endif()

set(content "#pragma once\n\n// Generated by cmake/DawBuildInfo.cmake at each build.\n#define DAW_BUILD_COMMIT \"${commit}\"\n#define DAW_BUILD_MODIFIED ${modified}\n")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
else()
    set(previous "")
endif()
if(NOT previous STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
